name: SOCIALMEDIA CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          echo "Triggering deployment on Render..."
          curl -X POST "https://api.render.com/deploy/srv-${RENDER_SERVICE_ID}" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{
            "envVars": [
              { "key": "MONGO_URI", "value": "'"$MONGO_URI"'" },
              { "key": "JWT_SECRET", "value": "'"$JWT_SECRET"'" }
            ]
          }'
